version: "3.7"

services:
  moodlehack:
    container_name: moodlehack
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - static:/static
    env_file:
      - ./moodlehack/.env
  ngnix:
    image: nginx:1.25.1-alpine
    container_name: moodlehack-web
    ports:
      - "80:80"
    volumes:
      - static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - moodlehack

volumes:
  static:
