services:
  moodlehack:
    container_name: moodlehack
    build:
      context: .
    expose:
      - 8000
    volumes:
      - static:/static
      - ./moodlehack/db.sqlite3:/app/db.sqlite3
    env_file:
      - ./moodlehack/.env
  ngnix:
    image: nginx:1.25.1-alpine
    container_name: moodlehack-web
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - moodlehack

volumes:
  static:
