"""
Django settings.
Generated by Pydantic-settings v2 system.
"""

from moodlehack.settings import cfg

# [django]
DEBUG = cfg.django.debug
SECRET_KEY = cfg.django.secret_key
ALLOWED_HOSTS = cfg.django.allowed_hosts
CSRF_TRUSTED_ORIGINS = cfg.django.csrf_trusted_origins
INTERNAL_IPS = cfg.django.internal_ips

AUTH_PASSWORD_VALIDATORS = cfg.django.auth_password_validators

INSTALLED_APPS = cfg.django.installed_apps
MIDDLEWARE = cfg.django.middleware
ROOT_URLCONF = cfg.django.root_urlconf
TEMPLATES = cfg.django.templates
# WSGI_APPLICATION = "moodlehack.core.wsgi.application"
# ASGI_APPLICATION = "moodlehack.core.asgi.application"

# [django.database]
DATABASES = cfg.django.database.as_dict

# [django.cache]
CACHES = cfg.django.cache.as_dict

# [django.i18n]
LANGUAGE_CODE = cfg.django.i18n.language_code
TIME_ZONE = cfg.django.i18n.time_zone
USE_I18N = cfg.django.i18n.use_i18n
USE_TZ = cfg.django.i18n.use_tz

# [django.static]
STATIC_URL = cfg.django.static.url
STATIC_ROOT = cfg.django.static.root
STATICFILES_DIRS = cfg.django.static.staticfiles_dirs
STATICFILES_FINDERS = cfg.django.static.staticfiles_finders

# [django.media]
MEDIA_URL = cfg.django.media.url
MEDIA_ROOT = cfg.django.media.root

# [django.data]
DATA_UPLOAD_MAX_NUMBER_FIELDS = cfg.django.data.data_upload_max_number_fields
DEFAULT_AUTO_FIELD = cfg.django.data.default_auto_field

# [django.email]
EMAIL_BACKEND = cfg.django.email.backend
EMAIL_HOST = cfg.django.email.host
EMAIL_PORT = cfg.django.email.port
EMAIL_HOST_USER = cfg.django.email.username
EMAIL_HOST_PASSWORD = cfg.django.email.password
EMAIL_USE_TLS = cfg.django.email.use_tls
EMAIL_USE_SSL = cfg.django.email.use_ssl

# --- Extensions Configuration ---

# [django.rest_framework]
REST_FRAMEWORK = cfg.django.rest_framework.as_dict

# [django.spectacular]
SPECTACULAR_SETTINGS = cfg.django.spectacular.as_dict

# [django.crispy]
CRISPY_ALLOWED_TEMPLATE_PACKS = cfg.django.crispy.allowed_template_packs
CRISPY_TEMPLATE_PACK = cfg.django.crispy.template_pack

# --- Custom Configuration ---

# [paths]
PATHS = cfg.paths.as_dict

# [uvicorn]
UVICORN = cfg.uvicorn.as_dict
