# Generated by Django 4.2.2 on 2026-01-12 12:31
# Edit by MOIS3Y on 2026-01-17 17:38
import django.db.models.deletion
from django.db import migrations, models

import moodlehack.answers.models


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0002_alter_period_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["-year", "-month", "update"],
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.AlterModelOptions(
            name="period",
            options={
                "ordering": ["-period"],
                "verbose_name": "Период (deprecated)",
                "verbose_name_plural": "Периоды (deprecated)",
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="month",
            field=models.IntegerField(
                choices=[
                    (1, "Январь"),
                    (2, "Февраль"),
                    (3, "Март"),
                    (4, "Апрель"),
                    (5, "Май"),
                    (6, "Июнь"),
                    (7, "Июль"),
                    (8, "Август"),
                    (9, "Сентябрь"),
                    (10, "Октябрь"),
                    (11, "Ноябрь"),
                    (12, "Декабрь"),
                ],
                default=moodlehack.answers.models.get_current_month,
                help_text="Месяц ответа (новая система)",
                verbose_name="Месяц",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="status",
            field=models.CharField(
                choices=[
                    ("actual", "Актуален"),
                    ("outdated", "Устарел"),
                    ("draft", "Черновик"),
                    ("review", "На проверке"),
                    ("unknown", "Неизвестно"),
                ],
                default="actual",
                help_text="Актуальность ответа",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (2026, "2026"),
                    (2027, "2027"),
                    (2028, "2028"),
                    (2029, "2029"),
                    (2030, "2030"),
                    (2031, "2031"),
                    (2032, "2032"),
                    (2033, "2033"),
                ],
                default=moodlehack.answers.models.get_current_year,
                help_text="Год в диапазоне 2023-2033 (новая система)",
                verbose_name="Год",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="actual",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Устаревшее поле. Будет удалено в будущей версии.",
                null=True,
                verbose_name="Актуален (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="create",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создан"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="Устаревшее поле. Будет удалено в будущей версии.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="answers.period",
                verbose_name="Период (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="update",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="period",
            name="period",
            field=models.DateField(
                blank=True,
                help_text="Устаревшее поле. Будет удалено в будущей версии.",
                null=True,
                verbose_name="Период (deprecated)",
            ),
        ),
    ]
