# Generated by Django 5.2.9 on 2026-01-18 13:58

import django.db.models.deletion
from django.db import migrations, models

import moodlehack.answers.models


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0003_alter_answer_options_alter_period_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["-year", "-month", "update"],
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="period",
            options={
                "ordering": ["-period"],
                "verbose_name": "Period (deprecated)",
                "verbose_name_plural": "Periods (deprecated)",
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="actual",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Deprecated field. Will be removed in future version.",
                null=True,
                verbose_name="Actual (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.TextField(verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="answers.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="create",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="month",
            field=models.IntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=moodlehack.answers.models.get_current_month,
                help_text="Answer month (new system)",
                verbose_name="Month",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="Deprecated field. Will be removed in future version.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="answers.period",
                verbose_name="Period (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.TextField(unique=True, verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="status",
            field=models.CharField(
                choices=[
                    ("actual", "Actual"),
                    ("outdated", "Outdated"),
                    ("draft", "Draft"),
                    ("review", "Under review"),
                    ("unknown", "Unknown"),
                ],
                default="actual",
                help_text="Answer relevance",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="tag",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Tag"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="update",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Source"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (2026, "2026"),
                    (2027, "2027"),
                    (2028, "2028"),
                    (2029, "2029"),
                    (2030, "2030"),
                    (2031, "2031"),
                    (2032, "2032"),
                    (2033, "2033"),
                ],
                default=moodlehack.answers.models.get_current_year,
                help_text="Year in range 2023-2033 (new system)",
                verbose_name="Year",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Category"
            ),
        ),
        migrations.AlterField(
            model_name="period",
            name="period",
            field=models.DateField(
                blank=True,
                help_text="Deprecated field. Will be removed in future version.",
                null=True,
                verbose_name="Period (deprecated)",
            ),
        ),
    ]
