# Generated by Django 5.2.9 on 2026-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "answers",
            "0004_alter_answer_options_alter_category_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional additional information about this answer.",
                verbose_name="Note",
            ),
        ),
    ]
