# Generated by Django 4.2.2 on 2024-09-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['-period'], 'verbose_name': 'Период', 'verbose_name_plural': 'Периоды'},
        ),
    ]
